django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop_items.urls'))
]

django_project/shop_items/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views


app_name = 'shop_items'
urlpatterns = [
    path('', views.ShopItemsView.as_view(), name='items'),
    path('<slug:slug>', views.SectionItemsView.as_view(), name='section_items'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/hitcount/models.py
from django.contrib.auth import get_user_model
from django.db import models

user = get_user_model()


class HitCount(models.Model):
    user = models.ForeignKey(user, on_delete=models.CASCADE, related_name='hit_count')
    url = models.CharField(max_length=500)
    count = models.IntegerField(default=1)
    
    def __str__(self):
        return f'{self.user} : {self.url}'
    
    class Meta:
        unique_together = ('user', 'url')

django_project/shop_items/models.py
import datetime

from django.db import models


class ShopItem(models.Model):
    """Товар в магазине"""
    
    title = models.CharField(max_length=100, db_index=True, verbose_name='Название товара')
    receipt_date = models.DateField(default=datetime.date.today, verbose_name='Дата поступления')
    price = models.DecimalField(decimal_places=2, max_digits=9, default=0, verbose_name='Цена товара')
    vendor_name = models.CharField(max_length=50, null=True, db_index=True, verbose_name='Имя поставщика')
    item_unit = models.CharField(max_length=10, verbose_name='Единица измерения', default='шт')
    
    def __str__(self):
        return self.title
    

django_project/shop_items/models/Section.py
from django.contrib.sites.managers import CurrentSiteManager
from django.contrib.sites.models import Site
from django.db import models


class Section(models.Model):
    """Раздел товаров"""
    
    title = models.CharField(max_length=50, db_index=True, unique=True, verbose_name='Название раздела')
    description = models.CharField(max_length=500, blank=True, verbose_name='Описание раздела')
    slug = models.SlugField()
    
    site = models.ForeignKey(Site, on_delete=models.CASCADE, null=True)
    objects = models.Manager()
    on_site = CurrentSiteManager('site')
    
    def __str__(self):
        return self.title

django_project/shop_items/models/ShopItem.py
import datetime

from django.contrib.sites.managers import CurrentSiteManager
from django.db import models
from . import Section
from django.contrib.sites.models import Site


class ShopItem(models.Model):
    """Товар в магазине"""
    
    title = models.CharField(max_length=100, db_index=True, verbose_name='Название товара')
    receipt_date = models.DateField(default=datetime.date.today, verbose_name='Дата поступления')
    price = models.DecimalField(decimal_places=2, max_digits=9, default=0, verbose_name='Цена товара')
    vendor_name = models.CharField(max_length=50, null=True, db_index=True, verbose_name='Имя поставщика')
    item_unit = models.CharField(max_length=10, verbose_name='Единица измерения', default='шт')
    image = models.ImageField(verbose_name='Изображение товара', upload_to='item_images', null=True)
    
    sections = models.ManyToManyField(Section, related_name='shop_items', verbose_name='Разделы')
    
    sites = models.ManyToManyField(Site, verbose_name='Принадлежность к сайтам')

    objects = models.Manager()
    on_site = CurrentSiteManager('sites')
    
    def __str__(self):
        return self.title

django_project/hitcount/views.py
from django.shortcuts import render

# Create your views here.

django_project/shop_items/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from shop_items.models import ShopItem, Section


class ShopItemsView(ListView):
    
    # queryset = ShopItem.objects.prefetch_related('sections').all()
    queryset = ShopItem.on_site.prefetch_related('sections').all()
    template_name = 'shop_items/shop_items_list.html'
    context_object_name = 'shop_items'
    
    
class SectionItemsView(ShopItemsView):
    
    def get_queryset(self):
        section_slug = self.kwargs.get('slug')
        # queryset = Section.objects.prefetch_related('shop_items').get(slug=section_slug).shop_items.all()
        queryset = Section.on_site.prefetch_related('shop_items').get(slug=section_slug).shop_items.all()
        return queryset
    

django_project/templates/base.html
{% load static %}
{% load section_tags %}

<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" defer></script>
    <title>{% block title %}Добро пожаловать{% endblock %}</title>
</head>
<body>
{% get_sections as context %}

<nav class="navbar navbar-light bg-light">
    <div class="container-fluid justify-content-start">
    <div>
        <a class="navbar-brand" href="/">Твой магазин</a>
        <p class="text-secondary">{{ context.site.name }}</p>
    </div>
        <div class="dropdown">
            <a class="btn btn-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
               data-bs-toggle="dropdown" aria-expanded="false">
                Разделы
            </a>

            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">

                {% for section in context.sections %}
                    <li><a class="dropdown-item"
                           href="{% url 'shop_items:section_items' section.slug %}">{{ section.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}

{% endblock %}

</body>
</html>

django_project/templates/shop_items/shop_items_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container m-5">

        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Фото</th>
                <th scope="col">Название</th>
                <th scope="col">Дата прибытия</th>
                <th scope="col">Единицы измерения</th>
                <th scope="col">Имя поставщика</th>
                <th scope="col">Цена</th>
                <th scope="col">Разделы</th>
            </tr>
            </thead>
            <tbody>
            {% for item in shop_items %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>

                    <td>{% if item.image %}
                        <img src="{{ item.image.url }}" alt="фото товара" style="width: 70px" class="rounded">
                    {% else %}
                        <img src="{% static 'defaul_item_image.jpg'%}" alt="фото товара" style="width: 70px" class="rounded">
                    {% endif %}
                    </td>
                    <td>{{ item.title }}</td>
                    <td>{{ item.receipt_date|date:'d M Y' }}</td>
                    <td>{{ item.item_unit }}</td>
                    <td>{{ item.vendor_name }}</td>
                    <td>{{ item.price }}</td>
                    <td>
                        {% if item.sections.all.count > 2 %}
                            <div class="dropdown">
                                <a class="text-decoration-none clear dropdown-toggle text-reset" href="#" role="button"
                                   id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ item.sections.all.first }}
                                </a>

                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    {% for section in item.sections.all %}
                                        <li>{{ section }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% else %}
                            {{ item.sections.all|join:' | ' }}
                        {% endif %}
                    </td>
                </tr>


            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}